/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 * @author Harim
 */
public class Correos extends javax.swing.JFrame {

    /**
     * Creates new form Correos
     */
    public Correos() {
        initComponents();
    }

    public DataInputStream flujoDatosEntrada;
    public DataOutputStream flujoDatosSalida;
    public String userId;

    /**
     * Persiste el id del usuario y los metodos para enviar y recibir datos por medio de una conexion previamente realizada
     *
     * @param DataInputStream input
     * @param DataOutputStream output
     * @param String id
     *
     * @return void
     */
    public void setInfo(DataInputStream DatosEntrada, DataOutputStream DatosSalida, String id) {
        userId = id;
        String leo;
        String recibo;
        Boolean aux = false;
        String ultimo;
        String remitente;
        String Asunto;
        String Cuerpo;
        String helper;
        try {
            System.out.println("llego al try:   " + DatosEntrada);
            leo = ("GETNEWMAILS" + " " + userId);
            System.out.println("lo que se metio en leo: " + leo);
            DatosSalida.writeUTF(leo);
            modelo = new DefaultTableModel();
            modelo.addColumn("Remitente");
            modelo.addColumn("Asunto");
            modelo.addColumn("Mensaje");
            jTable1.setModel(modelo);
            while (aux == false) {
                recibo = DatosEntrada.readUTF();
                System.out.println(recibo);
                String[] parts = recibo.split("'");
                helper = parts[0];
                String[] parts2 = helper.split(" ");
                remitente = parts2[4];
                Asunto = parts[1];
                Cuerpo = parts[3];
                modelo.addRow(new Object[]{remitente, Asunto, Cuerpo});
                int posicion = recibo.length() - 1;
                ultimo = recibo.substring(posicion);
                // System.out.println(ultimo);
                if (ultimo.equals("*")) {
                    System.out.println("entro");
                    aux = true;
                }
            }
        } catch (Exception e) {
            System.out.println("Excepcion producida :c   " + e);
        }
    }

    /**
     * Setea correos
     */
    public void setCorreos() {
        String leo;
        String recibo;
        Boolean aux = false;
        int auxx = 3;

        try {
            System.out.println("llego al try ");
            leo = ("GETNEWMAILS" + " " + userId);
            System.out.println("lo que se metio en leo: " + leo);
            flujoDatosSalida.writeUTF(leo);
            while (3 > auxx) {
                recibo = flujoDatosEntrada.readUTF();
                System.out.println(recibo);
            }

        } catch (Exception e) {
            System.out.println("Excepcion producida :c   " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Listado de correos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 920, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static DefaultTableModel modelo;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Correos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Correos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Correos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Correos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Correos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
