/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harim
 */
public class CrearCorreo extends javax.swing.JFrame {

    /**
     * Creates new form CrearCorreo
     */
    public CrearCorreo() {
        initComponents();
    }
        public DataInputStream flujoDatosEntrada;
    public DataOutputStream flujoDatosSalida;
    public String userId;
    ArrayList<String> destinatarios = new ArrayList<String>();
    private static DefaultTableModel modelo;
    private int contador = 0;
    
    public void setInfo(DataInputStream DatosEntrada, DataOutputStream DatosSalida, String id){
        flujoDatosEntrada = DatosEntrada;
        flujoDatosSalida = DatosSalida;
        userId = id;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Destinatarios:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Crear Correo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 70));

        jButton1.setText("Añadir");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 450, 290));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Cuerpo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Asunto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 450, 30));

        jButton2.setBackground(new java.awt.Color(48, 86, 191));
        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rocket.png"))); // NOI18N
        jButton2.setText("¡Enviar!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 210, 90));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 260, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String leo;
           String recibo;
           String aux;
           String username;
           String server;
        		try{
                        aux = jTextField3.getText();
                        String[] parts = aux.split("@");
                        username= parts[0];
                        server = parts[1];
                        System.out.println("llego al try:   "+ flujoDatosEntrada );
                        leo = ("VERIFYUSRSERVER" +" "+ username +" "+ server);
                        System.out.println("lo que se metio en leo: "+ leo);
                        flujoDatosSalida.writeUTF(leo);
                        recibo = flujoDatosEntrada.readUTF();
                        System.out.println(recibo); 
                        switch(recibo) {
                    case "SERVER : OK SERVER VERIFICATE":
                          destinatarios.add(jTextField3.getText());
                           if(contador == 0){
                           modelo = new DefaultTableModel();
                           modelo.addColumn("Destinatarios");
                          jTable1.setModel(modelo);
                           }
                              modelo.addRow(new Object[]{jTextField3.getText()});
                              contador = contador +1;
                        break;
                    case "SERVER : LOGIN ERROR 102":
                        JOptionPane.showMessageDialog(null, "Contraseña incorrecta, intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
                       // conexion.close();
                        break;
                    case "SERVER : LOGIN ERROR 101":
                        JOptionPane.showMessageDialog(null, "Usuario desconocido, intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
                       // conexion.close();
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Ha ocurrido un error desconocido, intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
                       // conexion.close();
                        break;
                }
                        }catch(Exception e){
			System.out.println("Excepcion producida :c   "+ e);
		}
        
    }//GEN-LAST:event_jButton1ActionPerformed

        private boolean validFields() {
        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() ||
                jTextField1.getText().trim().equals("") || jTextField2.getText().trim().equals("") || destinatarios.isEmpty()) {
            return false;
        }
        
        return true;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String recibo;
        		try{

                        if(validFields()){
            String leo = "SEND MAIL";
        System.out.println(leo);
        flujoDatosSalida.writeUTF(leo); 
        for(int x=0;x<destinatarios.size();x++) {
            if(x == destinatarios.size()-1){
                leo = "MAIL TO "+destinatarios.get(x)+" *";
                System.out.println(leo);
                flujoDatosSalida.writeUTF(leo); 
            }else{
                leo = "MAIL TO "+destinatarios.get(x);
                System.out.println(leo);
                flujoDatosSalida.writeUTF(leo); 
            }
        }
        leo = "MAIL SUBJECT "+jTextField1.getText();
        System.out.println(leo);
        flujoDatosSalida.writeUTF(leo); 
        leo = "MAIL BODY "+jTextField2.getText();
        System.out.println(leo);
        flujoDatosSalida.writeUTF(leo); 
        leo = "END SEND MAIL";
        System.out.println(leo);
        flujoDatosSalida.writeUTF(leo); 
        recibo = flujoDatosEntrada.readUTF();
        System.out.println(recibo);
        } else{
            JOptionPane.showMessageDialog(null, "No lleno todos los campos...", "Error", JOptionPane.ERROR_MESSAGE);
        }  
		}catch(Exception e){
			System.out.println("Excepcion producida :c   "+ e);
		}
             
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
