/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Harim
 */
public class Login extends javax.swing.JFrame {

    public DataInputStream flujoDatosEntrada;
    public DataOutputStream flujoDatosSalida;
    public String userId;
    public Socket conexion;
    
    public void setInfo(DataInputStream input, DataOutputStream output, Socket conexion) {
        flujoDatosEntrada = input;
        flujoDatosSalida = output;
        this.conexion = conexion;
    }
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/man (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 280, 270));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 190, 30));

        jButton2.setBackground(new java.awt.Color(48, 86, 191));
        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rocket.png"))); // NOI18N
        jButton2.setText("¡Go!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 160, 70));

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 190, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("18001882 - Harim Abdalá Palma Salvatierra");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("18001167 - Manuel José Santos Méndez");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("17001087 - José Carlos Loarca Hass");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("18002715 - Jair Alexander Flores Martínez");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("PROYECTO FINAL CC2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 20, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("User:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/people.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 20, 30));

        jLabelFondo.setBackground(java.awt.SystemColor.textHighlight);
        jLabelFondo.setForeground(java.awt.Color.white);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comettt.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validFields() {
        if(jTextField1.getText().isEmpty() || jPasswordField1.getText().isEmpty() ||
                jTextField1.getText().trim().equals("") || jPasswordField1.getText().trim().equals("")) {
            return false;
        }
        return true;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String user = jTextField1.getText().toLowerCase();
        String password = jPasswordField1.getText().toLowerCase();
        if( ! validFields()){
           JOptionPane.showMessageDialog(null, "Por favor complete ambos campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String leo;
            
            try{
               String aux = jTextField1.getText();
                        String[] parts = aux.split("@");
                        String username= parts[0];
                        String server = parts[1];
                if (verifyUserServer(flujoDatosEntrada, flujoDatosSalida, username, server)) {
                    leo = ("LOGIN" + " " + parts[0] +" "+ password);
                    flujoDatosSalida.writeUTF(leo); 
                    String response = flujoDatosEntrada.readUTF();

                    switch(response) {
                        case "SERVER : OK LOGIN":
                            Interfaz menu = new Interfaz();
                            menu.setUsername(username);
                            menu.setUserId(username, password, flujoDatosEntrada, flujoDatosSalida, conexion);
                            menu.setVisible(true);
                            this.setVisible(false);
                            break;
                        case "SERVER : LOGIN ERROR 102":
                            JOptionPane.showMessageDialog(null, "Contraseña incorrecta, intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
                            conexion.close();
                            break;
                        case "SERVER : LOGIN ERROR 101":
                            JOptionPane.showMessageDialog(null, "Usuario desconocido, intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
                            conexion.close();
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Ha ocurrido un error desconocido, intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
                            conexion.close();
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ingresado no existe en el servidor.", "Error", JOptionPane.ERROR_MESSAGE);
                    conexion.close();
                }
            }catch(Exception e){
                try {
                    conexion.close();
                } catch (IOException ex) {
                    System.out.println("No se puedo crear la conexion");
                }
		System.out.println("No se puedo crear la conexion");
            }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     *
     * @param flujoDatosEntrada
     * @param flujoDatosSalida
     * @param user
     * @param server
     * @return
     */
    public boolean verifyUserServer(DataInputStream flujoDatosEntrada, DataOutputStream flujoDatosSalida, String user, String server) {
        boolean verify = false;
        
        String reqStr = ("VERIFYUSRSERVER " + user + " " + server);
        
        System.out.println("Enviar: " + reqStr);
        
        try {
            flujoDatosSalida.writeUTF(reqStr);
            
            String response = flujoDatosEntrada.readUTF();
            
            System.out.println("Respuesta: " + response);
            
            switch(response) {
                case "SERVER : OK SERVER VERIFICATE": 
                    verify = true;
                    break;
                default:
                    break;
            }
            
            return verify;
            
        } catch (IOException ex) {
            System.out.println("Ocurrio un error al enviar los datos: " + ex);
        }
        
        return verify;
    }
    
    public void disableLoginButton() {
        jButton2.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
